# Generated by Django 4.0.6 on 2022-09-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
