# Generated by Django 4.0.6 on 2022-09-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studentmodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
        ),
    ]
